version: '3.6'
services:
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./data/grafana-provisioning/:/etc/grafana/provisioning
  python:
    container_name: python
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
      - 8883:8883
      - 1883:1883
    depends_on:
      - influxdb
      
volumes:
  grafana_data: {}
  influxdb_data: {}