version: '3.6'
services:
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    environment:
      INFLUXDB_DB: influx
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
  grafana:
    image: grafana/grafana:8.2.6
    container_name: grafana
    restart: always
    depends_on:
      - influxdb
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_LOG_LEVEL: ${GF_LOG_LEVEL}
      GF_INSTALL_PLUGINS:
    links:
      - influxdb
    ports:
      - '3000:3000'
    # volumes:
    #   - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
    #   - ./grafana/dashboards:/var/lib/grafana/dashboards
    #   - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
  python:
    container_name: python
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
      - 8883:8883
      - 1883:1883
    depends_on:
      - influxdb
      
volumes:
  grafana_data: {}
  influxdb_data: {}